//
// Created by DELL on 05-03-2024.
//

#ifndef RUBIKSCUBESOLVERPROJECT_GENERICRUBIKSCUBE_H
#define RUBIKSCUBESOLVERPROJECT_GENERICRUBIKSCUBE_H


class GenericRubiksCube {

};


#endif //RUBIKSCUBESOLVERPROJECT_GENERICRUBIKSCUBE_H
